### ISSUE TITLE
Getting API key

### ISSUE THREAD

**Issue by schrammalama** [EmuDeck/Emuchievements#1]
I was wondering how to get the RetroAchievements API key, I think I found where it should be but it just says not found.
It would be great to have some different documentation in the read me as well.

**Comment by Nisker** [comment]
On [retroachievements.org](https://retroachievements.org/controlpanel.php#) in the setting there's a field called `Web API Key` thats the API key this application wants.

If you dont get the key written correctly in gaming mode, it can also (in desktop mode) be pasted into a retroachievements file located in the homebrew folder.

**Comment by schrammalama** [comment]
Is it the emuchievements.json file? it has space for the username and API key but even once filling in out all it does is load/

**Comment by Nisker** [comment]
After making changes to the file you will need to reboot. That did the trick for me at least.

**Comment by Witherking25** [comment]
closing this as it seems to have already been resolved :)

**Comment by Witherking25** [comment]
also if you have a lot of games with achievements, it can take a while to load. working on rewriting a lot of stuff, so will be better s00n
