### ISSUE TITLE
Multiple achievements sources (i.e. Exophase)

### ISSUE THREAD

**Issue by joserzc** [EmuDeck/Emuchievements#13]
Are you familiar with Exophase? It'd be great if this Decky plugin shows achievements from different non-steam games services, such as Epic, GOG, Xbox and so on. I have recently started to use Exophase to track achievements, but I'm not sure if they have an API

**Comment by Witherking25** [comment]
I've not heard of it, I'll look into it

**Comment by Witherking25** [comment]
Unfortunately exophase does not have a public api I can hook into.
