### ISSUE TITLE
Suggestion on speeding up ROM scanning

### ISSUE THREAD

**Issue by wholee** [EmuDeck/Emuchievements#14]
Hi,

There is an API endpoint on retroachievements.org that returns all supported games and their associated systems and retrohashes:
`https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=1`
`f` = only games that have achievements
`h` = return hashes with game info
`i` = filter by console id
API_GetGameList can be called with any combination of "extra" arguments. Example above will only return supported games for MegaDrive with linked hashes.

Since (I'm guessing) most Steamdeck users that are using the Emuchievements plugin are also using Emudeck, I've compiled a list of all folders created by default Emudeck setup and added retroachievements consoldeID's on systems supported by them.

If a full supported games list is taken from `https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1` and ROM scans are only done on supported systems and checked against the list, that should greatly speed up the scanning.
Especially if you don't have to call retroachievements API for every single ROM to verify if retroachievements exist for it.

If this approach gets into consideration, I can also compile a list of ROM extensions for each supported system.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wholee/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wholee/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

System name | Emudeck folder | Retroachievements Console name | Retroachievements Console ID | Retroachievements registered games | Retroachievements registered hashes URL
-- | -- | -- | -- | -- | --
3DO | 3do | 3DO Interactive Multiplayer | 43 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=43
Adventure Game Studio Game Engine | ags |   |   |   |  
Commodore Amiga | amiga | Amiga | 35 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=35
Commodore Amiga 1200 | amiga1200 | Amiga | 35 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=35
Commodore Amiga 600 | amiga600 | Amiga | 35 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=35
Commodore Amiga CD32 | amigacd32 |   |   |   |  
Amstrad CPC | amstradcpc | Amstrad CPC | 37 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=37
Google Android | android |   |   |   |  
Apple II | apple2 | Apple II | 38 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=38
Apple IIGS | apple2gs | Apple II | 38 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=38
Arcade | arcade | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
Bally Astrocade | astrocde |   |   |   |  
Atari 2600 | atari2600 | Atari 2600 | 25 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=25
Atari 5200 | atari5200 | Atari 5200 | 50 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=50
Atari 7800 ProSystem | atari7800 | Atari 7800 | 51 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=51
Atari 800 | atari800 |   |   |   |  
Atari Jaguar | atarijaguar | Atari Jaguar | 17 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=17
Atari Jaguar CD | atarijaguarcd | Atari Jaguar CD | 77 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=77
Atari Lynx | atarilynx | Atari Lynx | 13 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=13
Atari ST | atarist | Atari ST | 36 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=36
Atari XE | atarixe |   |   |   |  
Atomiswave | atomiswave | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
BBC Micro | bbcmicro |   |   |   |  
Commodore 64 | c64 | Commodore 64 | 30 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=30
Cave Story (NXEngine) | cavestory |   |   |   |  
Philips CD-i | cdimono1 | Philips CD-i | 42 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=42
Commodore CDTV | cdtv |   |   |   |  
ChaiLove Game Engine | chailove |   |   |   |  
Fairchild Channel F | channelf | Fairchild Channel F | 57 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=57
Tandy Color Computer | coco |   |   |   |  
ColecoVision | colecovision | ColecoVision | 44 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=44
Capcom Play System | cps |   |   |   |  
Daphne Arcade LaserDisc Emulator | daphne |   |   |   |  
Desktop Applications | desktop |   |   |   |  
Doom | doom |   |   |   |  
DOS (PC) | dos | DOS | 26 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=26
Dragon 32 | dragon32 |   |   |   |  
Sega Dreamcast | dreamcast | Dreamcast | 40 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=40
EasyRPG Game Engine | easyrpg |   |   |   |  
Epic Games Store | epic |   |   |   |  
Nintendo Family Computer | famicom | NES | 7 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=7
FinalBurn Alpha | fba | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
FinalBurn Neo | fbneo | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
Nintendo Famicom Disk System | fds | NES | 7 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=7
Adobe Flash | flash |   |   |   |  
Fujitsu FM Towns | fmtowns | FM Towns | 58 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=58
Nintendo Game and Watch | gameandwatch | Game & Watch | 60 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=60
Sega Game Gear | gamegear | Game Gear | 15 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=15
Nintendo Game Boy | gb | Game Boy | 4 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=4
Nintendo Game Boy Advance | gba | Game Boy Advance | 5 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=5
Nintendo Game Boy Color | gbc | Game Boy Color | 6 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=6
Nintendo GameCube | gc | GameCube | 16 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=16
Sega Genesis | genesis | Mega Drive | 1 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=1
Amstrad GX4000 | gx4000 |   |   |   |  
Mattel Electronics Intellivision | intellivision | Intellivision | 45 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=45
Java 2 Micro Edition (J2ME) | j2me |   |   |   |  
Kodi Home Theatre Software | kodi |   |   |   |  
Lutris Open Gaming Platform | lutris |   |   |   |  
Lutro Game Engine | lutro |   |   |   |  
Apple Macintosh | macintosh |   |   |   |  
Multiple Arcade Machine Emulator | mame | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
AdvanceMAME | mame-advmame | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
MAME4ALL | mame-mame4all | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
Sega Master System | mastersystem | Master System | 11 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=11
Sega Mega-CD | megacd | Sega CD | 9 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=9
Sega Mega-CD | megacdjp | Sega CD | 9 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=9
Sega Mega Drive | megadrive | Mega Drive | 1 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=1
Creatronic Mega Duck | megaduck | Mega Duck | 69 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=69
Multi Emulator Super System | mess |   |   |   |  
Sega Model 2 | model2 |   |   |   |  
Sega Model 3 | model3 |   |   |   |  
Moonlight Game Streaming | moonlight |   |   |   |  
Thomson MO/TO Series | moto |   |   |   |  
MSX | msx | MSX | 29 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=29
MSX1 | msx1 | MSX | 29 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=29
MSX2 | msx2 | MSX | 29 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=29
MSX Turbo R | msxturbor | MSX | 29 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=29
M.U.G.E.N Game Engine | mugen |   |   |   |  
Othello Multivision | multivision |   |   |   |  
Nintendo 3DS | n3ds | Nintendo 3DS | 62 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=62
Nintendo 64 | n64 | Nintendo 64 | 2 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=2
Nintendo 64DD | n64dd | Nintendo 64 | 2 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=2
Sega NAOMI | naomi | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
Sega NAOMI GD-ROM | naomigd | Arcade | 27 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=27
Nintendo DS | nds | Nintendo DS | 18 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=18
SNK Neo Geo | neogeo |   |   |   |  
SNK Neo Geo CD | neogeocd | Neo Geo CD | 56 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=56
SNK Neo Geo CD | neogeocdjp | Neo Geo CD | 56 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=56
Nintendo Entertainment System | nes | NES | 7 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=7
SNK Neo Geo Pocket | ngp | Neo Geo Pocket | 14 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=14
SNK Neo Geo Pocket Color | ngpc | Neo Geo Pocket | 14 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=14
Magnavox Odyssey2 | odyssey2 | Magnavox Odyssey 2 | 23 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=23
OpenBOR Game Engine | openbor |   |   |   |  
Tangerine Computer Systems Oric | oric | Oric | 32 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=32
Palm OS | palm |   |   |   |  
IBM PC | pc |   |   |   |  
NEC PC-8800 Series | pc88 | PC-8000/8800 | 47 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=47
NEC PC-9800 Series | pc98 | PC-9800 | 48 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=48
NEC PC Engine | pcengine | PC Engine | 8 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=8
NEC PC Engine CD | pcenginecd | PC Engine CD | 76 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=76
NEC PC-FX | pcfx | PC-FX | 49 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=49
PICO-8 Fantasy Console | pico8 |   |   |   |  
Nintendo Pokémon Mini | pokemini | Pokemon Mini | 24 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=24
Ports | ports |   |   |   |  
Sony PlayStation 2 | ps2 | PlayStation 2 | 21 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=21
Sony PlayStation 3 | ps3 |   |   |   |  
Sony PlayStation 4 | ps4 |   |   |   |  
Sony PlayStation Portable | psp | PlayStation Portable | 41 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=41
Sony PlayStation Vita | psvita |   |   |   |  
Sony PlayStation | psx | PlayStation | 12 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=12
SAM Coupé | samcoupe |   |   |   |  
Nintendo Satellaview | satellaview | SNES | 3 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=3
Sega Saturn | saturn | Saturn | 39 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=39
Sega Saturn | saturnjp | Saturn | 39 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=39
ScummVM Game Engine | scummvm |   |   |   |  
Sega Mega Drive 32X | sega32x | 32X | 10 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=10
Sega Super 32X | sega32xjp | 32X | 10 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=10
Sega Genesis 32X | sega32xna | 32X | 10 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=10
Sega CD | segacd | Sega CD | 9 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=9
Nintendo SFC (Super Famicom) | sfc | SNES | 3 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=3
Sega SG-1000 | sg-1000 | SG-1000 | 33 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=33
Nintendo Super Game Boy | sgb | SNES | 3 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=3
Nintendo SNES (Super Nintendo) | snes | SNES | 3 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=3
Nintendo SNES (Super Nintendo) | snesna | SNES | 3 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=3
Solarus Game Engine | solarus |   |   |   |  
Spectravideo | spectravideo |   |   |   |  
Valve Steam | steam |   |   |   |  
Stratagus Game Engine | stratagus |   |   |   |  
Bandai SuFami Turbo | sufami |   |   |   |  
NEC SuperGrafx | supergrafx |   |   |   |  
Watara Supervision | supervision | Watara Supervision | 63 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=63
Nintendo Switch | switch |   |   |   |  
Symbian | symbian |   |   |   |  
Tano Dragon | tanodragon |   |   |   |  
NEC TurboGrafx-CD | tg-cd | PC Engine CD | 76 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=76
NEC TurboGrafx-16 | tg16 | PC Engine | 8 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=8
Texas Instruments TI-99 | ti99 |   |   |   |  
TIC-80 Game Engine | tic80 | TIC-80 | 65 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=65
Thomson TO8 | to8 | Thomson TO8 | 66 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=66
Tandy TRS-80 | trs-80 |   |   |   |  
Uzebox | uzebox |   |   |   |  
Vectrex | vectrex | Vectrex | 43 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=43
Commodore VIC-20 | vic20 | VIC-20 | 34 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=34
Philips Videopac G7000 | videopac |   |   |   |  
Nintendo Virtual Boy | virtualboy | Virtual Boy | 28 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=28
Nintendo Wii | wii | Wii | 19 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=19
Nintendo Wii U | wiiu | Wii U | 20 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=20
Nintendo Wii U | wiiu/roms (custom system) | Wii U | 20 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=20
Bandai WonderSwan | wonderswan | WonderSwan | 53 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=53
Bandai WonderSwan Color | wonderswancolor | WonderSwan | 53 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=53
Sharp X1 | x1 | Sharp X1 | 64 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=64
Sharp X68000 | x68000 | Sharp X68000 | 52 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=52
Microsoft Xbox | xbox | Xbox | 22 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=22
Microsoft Xbox 360 | xbox360 |   |   |   |  
Infocom Z-machine | zmachine |   |   |   |  
Sinclair ZX81 | zx81 | ZX81 | 31 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=31
Sinclair ZX Spectrum | zxspectrum | ZX Spectrum | 59 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=59
  |   | Cassette Vision | 54 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=54
  |   | Super Cassette Vision | 55 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=55
  |   | Nokia N-Gage | 61 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=61
  |   | PC-6000 | 67 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=67
  |   | Sega Pico | 68 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=68
  |   | Zeebo | 70 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=70
  |   | Arduboy | 71 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=71
  |   | WASM-4 | 72 |   | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=72
  |   | Arcadia 2001 | 73 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=73
  |   | Interton VC 4000 | 74 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=74
  |   | Elektor TV Games Computer | 75 | N/A | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=75
  |   | Nintendo DSi | 78 | Same as Nintendo DS (18) | https://retroachievements.org/API/API_GetGameList.php?z=_USERNAME_&y=_API_KEY_&f=1&h=1&i=78

</body>

</html>

Hope this helps in some way.

**Comment by Witherking25** [comment]
This will actually make things slower as I pointed out in the discord, closing
