### ISSUE TITLE
Consistently hangs on same Title

### ISSUE THREAD

**Issue by TheCyberQuake** [EmuDeck/Emuchievements#17]
Plugin never fully loads, consistently hangs on the same title. Can be left to load for hours but makes no progress.

Title:
Pokèmon Sword

Progress:
28/67

I get this issue on multiple EmuDeck plugins (the other notable one being MetaDeck, which hangs on a different title)
This issue has persisted across multiple Decky Loader versions, on both prerelease and stable, and has persisted across a full reimage.
I would greatly appreciate being pointed to any other details/logs I could grab that may help point us in the right direction to figuring out what's going on.

**Comment by TheCyberQuake** [comment]
Also of note, I'm running stable for Steam OS updates, on latest as of 6/28

**Comment by Wakyubi** [comment]
I have the same behavior always stopping on the 6th tittle 

Decky loader 2.10.4-pre2
Emuchievements - 2.0.2 

In addition the "Settings" is also stuck.

**Comment by Wakyubi** [comment]
I found a workaround.
1- Go to desktop mode then open emudeck
2- Go to the Steam room manager and remove the titles you added on Steam.
3- Go back to the Game mode and open the emu-achivements settings
4- Be sure you can log in, your user name and your api should be correct.
5- Once you can see the notification that you are logged in you can go back to desktop mode and re add all the game back again. If you can't see the notification, restart the console and try again.
6- Once all the games are back on steam you will be able to progress on your achievements, however the bug of the plugin will remain the same.
The settings will be inaccessible and the plugins will get stuck on loading the games, however this will not prevent you to progress you achievements when entering a game.

Let me know if someone had a different behavior. 
Decky loader 2.10.4-pre2
Emuchievements - 2.0.2

**Comment by Mandydeth** [comment]
I'm having the same issue. Mine hangs on the 19th title. Using v2.10.3 w/ 2.0.2

- Tried renaming it to see if it would change anything, but no luck.
- Attempted restarting - progresses to same game and stops
- Both reloading and reinstalling did not change anything

**Comment by Wakyubi** [comment]
> I'm having the same issue. Mine hangs on the 19th title. Using v2.10.3 w/ 2.0.2
> 
> * Tried renaming it to see if it would change anything, but no luck.
> * Attempted restarting - progresses to same game and stops
> * Both reloading and reinstalling did not change anything

Did you tried the fix above ?

**Comment by jangerhard** [comment]
I think I've spotted a infinite, recursive retry-strategy that can cause hangs on invalid game-ids (games that do not exist in retroachievements), and I've created a PR: #19

**Comment by Witherking25** [comment]
Yeah, but you won't get an invalid game id if the game doesn't exist, the id is retrieved from their servers based on a hash. If the game doesn't exist, it returns game id 0, and my code handles that and doesn't retry. If it returns an error however it will retry as the api is somewhat unreliable and can fail randomly. Also the api is down for maintenance right now so I can't really fix things until then, and likely things are even more broken (nonfunctional) as a result.

**Comment by Wakyubi** [comment]
> Yeah, but you won't get an invalid game id if the game doesn't exist, the id is retrieved from their servers based on a hash. If the game doesn't exist, it returns game id 0, and my code handles that and doesn't retry. If it returns an error however it will retry as the api is somewhat unreliable and can fail randomly. Also the api is down for maintenance right now so I can't really fix things until then, and likely things are even more broken (nonfunctional) as a result.

Noted, this ia definitely my favorite plug-in, hope will be 100 working soon. Thanks for the update

**Comment by soda3x** [comment]
This is still happening, is a fix in the works?

**Comment by Witherking25** [comment]
@soda3x Emuchievements won't and can't work until RetroAchievements servers are out of maintenance

**Comment by AtTimesChris** [comment]
Is this still the case as keeps happening when I try Emuchievements but keeps getting stuck, Same with MetaDeck. Keeps getting stuck think after 10 failed requests, currently on a YouTube shortcut keeps getting stuck without timing out to continue on to the next or anything.

**Comment by Wakyubi** [comment]
> Is this still the case as keeps happening when I try Emuchievements but keeps getting stuck, Same with MetaDeck. Keeps getting stuck think after 10 failed requests, currently on a YouTube shortcut keeps getting stuck without timing out to continue on to the next or anything.

Did you try following this ?

1- Go to desktop mode then open emudeck
2- Go to the Steam room manager and remove the titles you added on Steam.
3- Go back to the Game mode and open the emu-achivements settings
4- Be sure you can log in, your user name and your api should be correct.
5- Once you can see the notification that you are logged in you can go back to desktop mode and re add all the game back again. If you can't see the notification, restart the console and try again.
6- Once all the games are back on steam you will be able to progress on your achievements, however the bug of the plugin will remain the same.
**The settings will be inaccessible and the plugins will get stuck on loading the games, however this will not prevent you to progress you achievements when entering a game.**

**Comment by pipoliviero** [comment]
Still having the same issue. I've had this plugin pretty much since it came out and this has been exactly the same since day one. This plugin has never worked lmao.
