### ISSUE TITLE
Big problems with duplicate games from different Emulators

### ISSUE THREAD

**Issue by Leblayd** [EmuDeck/Emuchievements#21]
I am getting this error:
`Error reference: Shared SteamUI_8600801_8e42dcc152dcbedf`
`Cannot destructure property 'cEarned' of 'p' as it is undefined.`

First, I also want to say that I can see the list of achievements on each game's own page, *but* none of them are shown as achieved.

And it happens in a variety of situations. Most consistently, when I open the plugin itself, and then click on any game.
Pressing refresh once and then B to go back solves this. BUT after that point, all emulated games that have achievements are gone from the library. A restart and then opening the Emuchievements plugin page *but not opening any game there* fixes this, **but** brings back duplicates. And interestingly, these duplicates now *all* show the achievements I do and don't have on the game's page.

I **think** it might be related to the following:
I have duplicate games. I ran Steam Rom Manager once while I had 3 of each PS1 game, one for each available emulator.
I went into game mode, realized the mistake and immediately went back to fix it. But Emuchievements didn't pick up that change, and since then I have duplicates, and they all show up with the same amount of achievements.

(I have even worse problems when I press the Steam button while in-game. No Steam UIs show up afterward, including the volume slider and hotkey popup, etc. The UI also doesn't make sounds so it's not just invisible, either, but entirely gone. I cannot even exit the game, I have to long press the power button and restart.)
![download](https://github.com/EmuDeck/Emuchievements/assets/33326417/9510d29f-8783-48d2-80f3-d12837cbacfb)
![download (1)](https://github.com/EmuDeck/Emuchievements/assets/33326417/80e3266e-1640-47d8-ac85-f6e89e81a547)

**Comment by Witherking25** [comment]
Try deleting your config, (or just the cache element if you know how json works).
