### ISSUE TITLE
No games linked after scan and no achievements found

### ISSUE THREAD

**Issue by cynojien** [EmuDeck/Emuchievements#36]
I tried this plugin today. I put in my username and API key without any issue. I got the popup stating that the login was successful.

I was able to see the plugin scan through all the shortcuts but every game it scanned would show "No Achievements Found" and nothing came up after it had finished.

I tried both the Default and Testing versions.

Do the shortcuts have to be added a certain way? All of my games are shell scripts that launch the actual game in case I have to change something in the future as I don't have to worry about steam shortcuts breaking.

I checked the setting.json file and every shortcut is listed like "2170676549": null,

I have both Dolphin and non-Dolphin games on my profile at retroachievements.

**Comment by KP2048** [comment]
Games cannot be in shell scripts. The plugin parses the launch command to find the ROM file to hash

**Comment by KP2048** [comment]
One way you could get around this would be to put the rom path in the launch command somewhere where it won't be used, that way the regex will still pick it up but the game is still executed from your script. You could append `; ls <rom path> 2>&1 > /dev/null` to the end of the steam launch command to trick the parser for instance.

**Comment by KP2048** [comment]
You could also have a single script per emulator and pass the rom path as an argument, that would also work.

**Comment by cynojien** [comment]
I had a sneaking suspicion that that might have been related to it. I just tried it with your idea of just having each script point to the emulator. It seems to be working now. Thank you! I'll close.
