### ISSUE TITLE
Gets Stuck Loading

### ISSUE THREAD

**Issue by samcs1111** [EmuDeck/Emuchievements#8]
It gets stuck on the first title and settings doesn’t work anymore and I’ve reinstalled it and checked the json file.

![7916FF0E-B7A0-4CA5-A4D3-C8C08AE70003](https://user-images.githubusercontent.com/58991190/230775823-c950f00e-a7ff-427a-92c3-04c3357b1be4.jpeg)
![AC3E3C54-FD57-41B9-9632-9AAA9544F629](https://user-images.githubusercontent.com/58991190/230775826-62615142-bee5-4eea-8167-4b0ab824bd3f.jpeg)

**Comment by samcs1111** [comment]
I’ve just rechecked the json file and it’s empty so this could be the reason why it’s playing up. I’ve reinstalled the plug-in but it hasn’t restored.

**Comment by cookandy** [comment]
I'm also experiencing this issue. In my case I do have a valid JSON file at `/home/deck/homebrew/settings/emuchievements.json`, which looks like this 

```json
{
    "username": "cookandy",
    "api_key": "xxxx",
    "hidden": false
}
```

The plugin just spins saying "Loading" and "Fetching". Any ideas?

**Comment by samcs1111** [comment]
I’ve just rechecked my JSON file and it has regenerated itself with my valid information but it is doing the same thing

**Comment by CleitonDeLima** [comment]
same problem here :/

**Comment by redbeardymcgee** [comment]
I'm experiencing the same issue, but the plugin **looks like** it's still working on initial game searches. I don't remember when any progress was made, but I noticed tonight that it's at 36/38 games. What 38 games? I don't know. Non-Steam titles I guess.

I let it sit with the game open that it's currently searching for (or appears to be searching for) for about 15 minutes with no progress.

**Comment by jukefr** [comment]
same here for what this useless comment is worth but there doesn't seem to be any kinds of attention brought to this issue so 🤷

**Comment by samcs1111** [comment]
> same here for what this useless comment is worth but there doesn't seem to be any kinds of attention brought to this issue so 🤷

It’s good to know that I’m not the person having the issue though. I really hope the developers are aware of it.

**Comment by jukefr** [comment]
Also tried manually editing

```
/home/deck/homebrew/emuachievements.json
```

With my retroachievements username

And my "web api key" available here https://retroachievements.org/controlpanel.php

Same forever loading issue

**Comment by samcs1111** [comment]
Emuchievements is now working as it should for me on version 2.0.2
